version: '3.9'

services:
  catalog-db:
    image: mysql:8.0.33
    container_name: catalog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: cataloguser
      MYSQL_PASSWORD: catalogpass
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m